name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_PLUGIN_UPLOAD_ROLE_ARN }}
          aws-region: us-west-2

      - name: Upload managed plugin
        uses: ./.github/actions/upload_managed_plugin
        with:
          aws_region: us-west-2
          aws_s3_bucket: rpk-plugins-repo
          artifacts_file: target/dist/artifacts.json
          metadata_file: target/dist/metadata.json
          project_root_dir: ${{ github.workspace }}
          plugin_name: check
          goos: linux,darwin
          goarch: amd64,arm64
          repo_hostname: rpk-plugins.redpanda.com
          dry_run: "false"
